# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 18:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_auto_20160224_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'EmailTokens',
                'verbose_name': 'EmailToken',
            },
        ),
        migrations.CreateModel(
            name='PasswordToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PasswordTokens',
                'verbose_name': 'PasswordToken',
            },
        ),
        migrations.RemoveField(
            model_name='verificationtoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='VerificationToken',
        ),
    ]
