# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 04:22
from __future__ import unicode_literals

import credits.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('used', models.BooleanField(default=False)),
                ('expiration', models.DateTimeField(default=credits.models.set_expiration)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Credits',
                'ordering': ['-timestamp'],
                'verbose_name': 'Credit',
            },
        ),
    ]
