# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-21 19:59
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=2)),
                ('number', models.CharField(max_length=10)),
                ('duration', models.IntegerField()),
                ('cabin', models.CharField(choices=[('COACH', 'COACH'), ('PREMIUM_COACH', 'PREMIUM_COACH'), ('BUSINESS', 'BUSINESS'), ('FIRST', 'FIRST')], max_length=13)),
                ('booking_code', models.CharField(max_length=1)),
                ('married_group', models.CharField(max_length=1)),
                ('connection_duration', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Flight',
                'ordering': ['-timestamp'],
                'verbose_name_plural': 'Flights',
            },
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft', models.CharField(max_length=10)),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('origin', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=3)),
                ('duration', models.IntegerField()),
                ('on_time_performance', models.IntegerField(blank=True, null=True)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('meal', models.CharField(default='', max_length=120)),
                ('secure', models.BooleanField(default=True)),
                ('connection_duration', models.IntegerField(blank=True, null=True)),
                ('change_plane', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='trips.Flight')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trip',
                'ordering': ['-timestamp'],
                'verbose_name_plural': 'Trips',
            },
        ),
        migrations.CreateModel(
            name='TripPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ptc', models.CharField(default='', max_length=10)),
                ('refundable', models.BooleanField(default=False)),
                ('last_ticket_time', models.DateTimeField()),
                ('fare_calculation', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='trips.Trip')),
            ],
            options={
                'verbose_name': 'TripPrice',
                'ordering': ['-timestamp'],
                'verbose_name_plural': 'TripPrices',
            },
        ),
        migrations.CreateModel(
            name='TripStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=True)),
                ('is_passenger_ready', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=False)),
                ('is_purchased', models.BooleanField(default=False)),
                ('is_booked', models.BooleanField(default=False)),
                ('is_ticketed', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trips.TripStatus'),
        ),
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flight',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='trips.Trip'),
        ),
    ]
