# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 19:25
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.CharField(max_length=12)),
                ('cheapest_price', models.CharField(max_length=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trip',
                'ordering': ['-timestamp'],
                'verbose_name_plural': 'Trips',
            },
        ),
        migrations.CreateModel(
            name='TripSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_trip', models.BooleanField(default=True)),
                ('passenger', django.contrib.postgres.fields.jsonb.JSONField()),
                ('origin', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=10)),
                ('cabin', models.CharField(choices=[('COACH', 'COACH'), ('PREMIUM_COACH', 'PREMIUM_COACH'), ('BUSINESS', 'BUSINESS'), ('FIRST', 'FIRST')], max_length=13)),
                ('departure_time', models.CharField(max_length=5)),
                ('carrier', models.CharField(max_length=2)),
                ('price', models.CharField(max_length=12)),
                ('trip_option', django.contrib.postgres.fields.jsonb.JSONField()),
                ('expiration', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TripSearch',
                'ordering': ['-timestamp'],
                'verbose_name_plural': 'TripSearches',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_search',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='trips.TripSearch'),
        ),
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
