# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripstatus',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
