# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-21 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripExpectedPassengers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_count', models.IntegerField(default=0)),
                ('child_count', models.IntegerField(default=0)),
                ('infant_in_lap_count', models.IntegerField(default=0)),
                ('infant_in_seat_count', models.IntegerField(default=0)),
                ('senior_count', models.IntegerField(default=0)),
                ('trip_price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expected_passengers', to='trips.TripPrice')),
            ],
        ),
    ]
