db:
    image:  postgres
    ports:
      - "5432:5432"
web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    # dockerfile: ./docker/django/Dockerfile
    volumes:
      - .:/app
    links:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./env/dev.txt
