db:
    image:  postgres:9.4
    ports:
      - "5432:5432"
web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    links:
      - db
    env_file:
      - ./env/dev.txt
