# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1),
        ),
    ]
